# dataset config
dataset: 'glossyreal'
dataset_path: '../data/GlossyReal/bunny'


# volume rendering config
aabb: [-1,-1,-1,1,1,1]
    # [-1,-1,-1,1,1,1] for bunny, vase
    # [-0.75, -0.684, -0.49, 0.75, 0.816, 1.01] for bear
    # [-1.5, -1.5, -1.5, 1.5, 1.5, 1.5] for coral, maneki

render_step_size: 5e-3
render_step_size_n: 5e-2 # initial near-field feature step size
render_step_size_bkgd: 1e-2

batch_size: 512 # initial batch_size
target_sample_batch_size: 32768 #1<<15


# model config
sdf:
    num_encode: 6
    D: 8
    C: 256
    S: [4]
    weight_norm: True

nde:
    Cx: 16
    mlp_d: [64,64]
    far:
        C: 16
        H: 64
        L: 6
    near:
        C: 16
        H: 512
        L: 9
        mlp: [64]
    human:
        C: 16
        H: 256
        L: 8
        mlp: [64]
    pre_decode: False


# optimizer config
optimizer: 'Adam'
learning_rate: 5e-4
weight_decay: 0.0 # never used
scheduler_rate: 0.5
milestones: [10000]